# Generated by Django 4.2 on 2025-11-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('client_id_mqtt', models.CharField(default='ESP_CLIENT_ID', max_length=50, unique=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dispositivo IoT',
                'verbose_name_plural': 'Dispositivos IoT',
            },
        ),
        migrations.CreateModel(
            name='NivelReservatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registo de Nível',
                'verbose_name_plural': 'Registos de Nível',
                'ordering': ['-data_registro'],
            },
        ),
    ]
