# Generated by Django 4.2 on 2025-11-16 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Dispositivo')),
                ('device_id', models.CharField(max_length=50, unique=True, verbose_name='ID Único')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField(help_text='Nível de água em porcentagem (0-100)', verbose_name='Nível (%)')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Registro')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_app.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Registro de Sensor',
                'verbose_name_plural': 'Registros de Sensor',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.DeleteModel(
            name='Dispositivo',
        ),
        migrations.DeleteModel(
            name='NivelReservatorio',
        ),
    ]
