# Generated by Django 4.2 on 2025-11-16 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0002_device_sensordata_delete_dispositivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('ACTUATOR', 'Atuador'), ('LIGHT', 'Luz'), ('SWITCH', 'Interruptor')], default='SENSOR', max_length=20, verbose_name='Tipo de Dispositivo'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Vez Visto'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ERROR', 'Com Erro')], default='OFFLINE', max_length=20, verbose_name='Status'),
        ),
    ]
