# Generated by Django 4.2 on 2025-11-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0003_device_device_type_device_last_seen_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('NIVEL', 'Sensor de Nível'), ('PRESSAO', 'Sensor de Pressão'), ('VAZAO', 'Sensor de Vazão'), ('VALVULA', 'Válvula Solenoide')], default='SENSOR', max_length=20, verbose_name='Tipo de Dispositivo'),
        ),
    ]
